### ISSUE TITLE
autoGenerate is not working in (@PrimaryKey)

### ISSUE THREAD

**Issue by A7mdFathi** [pinchbv/floor#628]

**Comment by michelemazzei** [comment]
Hi, I have the same problem.
I have defined a simple entity class like  : 

    @immutable
    @entity
    class Category {
        @PrimaryKey(autoGenerate: true)
        final int id;
        final String name;
        final String description;
    ....
    }

The generated code for insertion Adapter is  :  

    _categoryInsertionAdapter = InsertionAdapter(
        database,
        'Category',
            (Category item) => <String, Object?>{
                'id': item.id,
                    'name': item.name,
                    'description': item.description,
                     .....
                    }),

I think it is wrong because the ID parameter must not be passed to SQLite, because the ID is AUTOINCREMENT.
(more over should be  INTEGER PRIMARY KEY, and if the key is not given in Insert query, then the db will calculate the next available integer).
Thus the mapper should not include the id.
If I remove "by hand"  the id, the adapter would not work because it wants the ID column value.
If I put a "zero" value as  ID to my Category object to persist, and I make it twice, the db would raise an exception as "duplicate key" (that's correct from db the point of view!).
If I put null as ID to the Category object, it does not work.

What do I wrong ?
Thanx

**Comment by dkaera** [comment]
@michelemazzei Try to define a nullable `id` as in the example project.
The main idea is to set it to `null` if you need to automatically generate an ID with SQLite. Here is a [link](https://www.sqlite.org/autoinc.html#:~:text=a%20value%20of-,NULL,-%2C%20then%20an%20appropriate) that explains how it works.
I think Floor documentation provides a wrong sample,  which causes this misunderstanding. We need to update it.

**Comment by dkaera** [comment]
Problem solved.
