### ISSUE TITLE
Support Analyzer 3

### ISSUE THREAD

**Issue by caoyanglee** [pinchbv/floor#667]
analyzer ^3.0.0

**Comment by ThomasMiddel** [comment]
Hey @caoyanglee! I'm currently working to get Floor up and running again, I [opened a PR](https://github.com/vitusortner/floor/pull/662) to support analyzer 4.1.0. The idea is to get this merged ASAP and roll out an update within a couple of days.

**Comment by vitusortner** [comment]
@caoyanglee do you have a specific use case for analyzer 3.0.0 or are you fine with analyzer 4.0.0?

**Comment by elirehema** [comment]
@vitusortner floor generator is conflicting with chopper generator 

> Because floor_generator >=1.3.0 depends on analyzer ^4.0.0 and chopper_generator 4.0.5 depends on analyzer ^3.0.0, floor_generator >=1.3.0 is incompatible with chopper_generator 4.0.5.
And because no versions of chopper_generator match >4.0.5 <5.0.0, floor_generator >=1.3.0 is incompatible with chopper_generator ^4.0.5.
So, because mobile depends on both chopper_generator ^4.0.5 and floor_generator ^1.3.0, version solving failed.
pub get failed (1; So, because mobile depends on both chopper_generator ^4.0.5 and floor_generator ^1.3.0, version solving failed.)

**Comment by dkaera** [comment]
@elirehema Chopper team has already pushed [PR with analyzer update](https://github.com/lejard-h/chopper/pull/340/files).

**Comment by elirehema** [comment]
Okay.
Thanks @dkaera

**Comment by caoyanglee** [comment]
> @caoyanglee do you have a specific use case for analyzer 3.0.0 or are you fine with analyzer 4.0.0?

both are ok~
