### ISSUE TITLE
Insert builk with OnConflictStrategy.replace is locking all tables 

### ISSUE THREAD

**Issue by nawaf11** [pinchbv/floor#695]
When I am inserting bulk (huge numbers around 77429 records) it's blocking other tables !

I have insert like this:

```
  @Insert(onConflict: OnConflictStrategy.replace)
  Future<void> insertList(List<TB_WordTranslation> list);
```

Now when I am getting all records from TB_Translations like this:

```
  @Query('SELECT * FROM $TABLE_NAME')
  Future<List<TB_Translations>> findAll();
```
it is not returning the data until the insertBulk finish.

**Comment by dkaera** [comment]
Hey @nawaf11 
That's too many entries for one operation. Do you really need all this data at once?
Generally, `sqflite` uses synchronized read-write operations, so you can't insert data and fetch results in parallel. Otherwise, Android will throw an IllegalStateException that you are trying to use more than one connection to the database. For IOS parallel work is configurable, but we don't support it.
So, if possible, try splitting the records into chunks and inserting them in parts. To observe the data changes, you can create a Stream in DAO that returns the actual records to you immediately after insertion.

**Comment by dkaera** [comment]
looks like problem solved
